import axios from 'axios'
import iziToast from 'izitoast'
import React, { useEffect, useState } from 'react'
import { FaBuilding, FaEnvelope, FaGlobe, FaPhoneAlt, FaSave } from 'react-icons/fa'

const blankCompany = { company_name: '', email: '', phone: '', website: '', address: '', gst_number: '' }
const valueOf = (source, keys) => keys.map((key) => source?.[key]).find((value) => value !== undefined && value !== null) || ''

export default function MyCompany() {
  const [company, setCompany] = useState(blankCompany)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  useEffect(() => { axios.get(`${import.meta.env.VITE_API_BASE_URL}/auth/company`).then(({ data }) => { const source = data?._data || data?.data || {}; setCompany({ company_name: valueOf(source, ['company_name', 'name']), email: valueOf(source, ['email']), phone: valueOf(source, ['phone', 'mobile_number']), website: valueOf(source, ['website']), address: valueOf(source, ['address']), gst_number: valueOf(source, ['gst_number', 'gst']) }) }).catch(() => iziToast.error({ message: 'Company details load nahi ho payi.' })).finally(() => setLoading(false)) }, [])
  const updateField = (event) => setCompany((current) => ({ ...current, [event.target.name]: event.target.value }))
  const submitHandler = (event) => { event.preventDefault(); if (!company.company_name.trim()) return iziToast.error({ message: 'Company name required hai.' }); setSaving(true); axios.put(`${import.meta.env.VITE_API_BASE_URL}/auth/company`, company).then(({ data }) => data?._status ? iziToast.success({ message: data._message || 'Company details updated successfully.' }) : iziToast.error({ message: data?._message || 'Company details update nahi ho payi.' })).catch((error) => iziToast.error({ message: error.response?.data?._message || 'Company details update nahi ho payi.' })).finally(() => setSaving(false)) }
  return <section className="mx-auto w-full max-w-6xl"><header className="mb-7 border-b border-slate-200 pb-6"><h1 className="text-4xl font-bold text-slate-950">My Company</h1><p className="mt-2 text-lg text-slate-500">Apne business ki public contact details update karein.</p></header><form onSubmit={submitHandler} className="overflow-hidden rounded-2xl bg-white shadow-xl shadow-slate-200/70"><div className="flex items-center gap-4 bg-gradient-to-r from-slate-900 to-indigo-800 px-6 py-7 text-white"><span className="grid h-14 w-14 place-items-center rounded-xl bg-white/15 text-2xl"><FaBuilding /></span><div><h2 className="text-2xl font-bold">Company information</h2><p className="text-indigo-100">Business identity and contact settings</p></div></div><div className="grid grid-cols-1 gap-6 p-6 sm:p-8 md:grid-cols-2"><CompanyField label="Company name" name="company_name" value={company.company_name} onChange={updateField} icon={FaBuilding} required /><CompanyField label="Business email" name="email" type="email" value={company.email} onChange={updateField} icon={FaEnvelope} /><CompanyField label="Phone number" name="phone" value={company.phone} onChange={updateField} icon={FaPhoneAlt} /><CompanyField label="Website" name="website" type="url" value={company.website} onChange={updateField} icon={FaGlobe} placeholder="https://example.com" /><CompanyField label="GST number" name="gst_number" value={company.gst_number} onChange={updateField} icon={FaBuilding} /><label className="block text-sm font-bold text-slate-700 md:col-span-2">Business address<textarea name="address" value={company.address} onChange={updateField} rows="4" className="mt-2 block w-full resize-none rounded-lg border border-slate-300 px-3 py-3 font-medium text-slate-700 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" placeholder="Enter company address" /></label><div className="flex justify-end md:col-span-2"><button disabled={loading || saving} className="flex items-center gap-2 rounded-lg bg-indigo-600 px-6 py-3 font-bold text-white hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-60"><FaSave /> {saving ? 'Saving...' : 'Save company details'}</button></div></div></form></section>
}

function CompanyField({ label, icon: Icon, ...props }) { return <label className="block text-sm font-bold text-slate-700">{label}<div className="relative mt-2">{React.createElement(Icon, { className: 'absolute left-3 top-1/2 -translate-y-1/2 text-slate-400' })}<input {...props} className="block w-full rounded-lg border border-slate-300 py-3 pl-10 pr-3 font-medium text-slate-700 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" /></div></label> }
